### ISSUE TITLE
Update body fonts to Inter, Always set heading fonts to Aktiv Grotesk Ex Semibold

### ISSUE THREAD

**Issue by tobimori** [tolocar-project/website#46]

**Comment by pReya** [comment]
Should be fixed by now.

**Comment by tobimori** [comment]
It's still not consistent with the design. Please check again.

**Comment by tobimori** [comment]
Website
<img width="571" alt="CleanShot 2023-02-02 at 12 20 46@2x" src="https://user-images.githubusercontent.com/29142128/216311334-3a037640-e540-41e5-8ef8-ddf08e6f592d.png">

Design
<img width="1052" alt="CleanShot 2023-02-02 at 12 20 50@2x" src="https://user-images.githubusercontent.com/29142128/216311353-db6af6f5-2b77-40fb-9cc1-7d730ab7435c.png">

--- 

Website
<img width="611" alt="CleanShot 2023-02-02 at 12 21 05@2x" src="https://user-images.githubusercontent.com/29142128/216311412-04911449-1b54-4c6c-9d22-c0261c67f237.png">

Design
<img width="988" alt="CleanShot 2023-02-02 at 12 21 14@2x" src="https://user-images.githubusercontent.com/29142128/216311455-fe803b66-605b-4061-a1e3-a2c4237c7469.png">

--- 

Website
<img width="384" alt="CleanShot 2023-02-02 at 12 22 13@2x" src="https://user-images.githubusercontent.com/29142128/216311715-b8251580-6288-4b23-9f03-b7ecd5c03685.png">

Design
<img width="1053" alt="CleanShot 2023-02-02 at 12 22 07@2x" src="https://user-images.githubusercontent.com/29142128/216311694-a819b5be-3cc2-4fb7-b3e8-965fa7d4b767.png">

---

Website
<img width="583" alt="CleanShot 2023-02-02 at 12 23 04@2x" src="https://user-images.githubusercontent.com/29142128/216311910-e4b08f3c-116e-4da2-9d4c-6c8790214242.png">

Design
<img width="532" alt="CleanShot 2023-02-02 at 12 23 14@2x" src="https://user-images.githubusercontent.com/29142128/216311929-4b8de6f8-c343-4b5f-a098-0f24301208ce.png">




For a general rule: 
- If a text is at the normal body size, use Inter.
- If a text is larger than the normal body size, use Aktiv Grotesk Ex Semibold.

**Comment by tobimori** [comment]
Not sure if these are all occasions, but it's everything I glanced in a quick overview.

**Comment by tobimori** [comment]
<img width="419" alt="CleanShot 2023-02-02 at 12 39 00@2x" src="https://user-images.githubusercontent.com/29142128/216315046-35174aa5-627a-4011-8d12-a5841123ddb8.png">
Mobile nav has wrong heading as well.

**Comment by pReya** [comment]
@Agustina-Carrion Can you add this to the global headline selector inside the `body` in `base.css:130`?
